// Code generated by protoc-gen-go.
// source: connector/grpc/grpc.proto
// DO NOT EDIT!

/*
Package grpc is a generated protocol buffer package.

It is generated from these files:
	connector/grpc/grpc.proto

It has these top-level messages:
	UserPassword
	UserID
	IdentityMessage
*/
package grpc

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserPassword struct {
	Username string `protobuf:"bytes,1,opt,name=username" json:"username,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *UserPassword) Reset()                    { *m = UserPassword{} }
func (m *UserPassword) String() string            { return proto.CompactTextString(m) }
func (*UserPassword) ProtoMessage()               {}
func (*UserPassword) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserPassword) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UserPassword) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UserID struct {
	Userid string `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
}

func (m *UserID) Reset()                    { *m = UserID{} }
func (m *UserID) String() string            { return proto.CompactTextString(m) }
func (*UserID) ProtoMessage()               {}
func (*UserID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserID) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

type IdentityMessage struct {
	Userid   string `protobuf:"bytes,1,opt,name=userid" json:"userid,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username" json:"username,omitempty"`
	Email    string `protobuf:"bytes,3,opt,name=email" json:"email,omitempty"`
}

func (m *IdentityMessage) Reset()                    { *m = IdentityMessage{} }
func (m *IdentityMessage) String() string            { return proto.CompactTextString(m) }
func (*IdentityMessage) ProtoMessage()               {}
func (*IdentityMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *IdentityMessage) GetUserid() string {
	if m != nil {
		return m.Userid
	}
	return ""
}

func (m *IdentityMessage) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *IdentityMessage) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*UserPassword)(nil), "grpc.UserPassword")
	proto.RegisterType((*UserID)(nil), "grpc.UserID")
	proto.RegisterType((*IdentityMessage)(nil), "grpc.IdentityMessage")
}

func init() { proto.RegisterFile("connector/grpc/grpc.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 190 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x92, 0x4c, 0xce, 0xcf, 0xcb,
	0x4b, 0x4d, 0x2e, 0xc9, 0x2f, 0xd2, 0x4f, 0x2f, 0x2a, 0x48, 0x06, 0x13, 0x7a, 0x05, 0x45, 0xf9,
	0x25, 0xf9, 0x42, 0x2c, 0x20, 0xb6, 0x94, 0x4c, 0x7a, 0x7e, 0x7e, 0x7a, 0x4e, 0xaa, 0x7e, 0x62,
	0x41, 0xa6, 0x7e, 0x62, 0x5e, 0x5e, 0x7e, 0x49, 0x62, 0x49, 0x66, 0x7e, 0x5e, 0x31, 0x44, 0x8d,
	0x92, 0x1b, 0x17, 0x4f, 0x68, 0x71, 0x6a, 0x51, 0x40, 0x62, 0x71, 0x71, 0x79, 0x7e, 0x51, 0x8a,
	0x90, 0x14, 0x17, 0x47, 0x69, 0x71, 0x6a, 0x51, 0x5e, 0x62, 0x6e, 0xaa, 0x04, 0xa3, 0x02, 0xa3,
	0x06, 0x67, 0x10, 0x9c, 0x0f, 0x92, 0x2b, 0x80, 0xaa, 0x93, 0x60, 0x82, 0xc8, 0xc1, 0xf8, 0x4a,
	0x0a, 0x5c, 0x6c, 0x20, 0x73, 0x3c, 0x5d, 0x84, 0xc4, 0xb8, 0xd8, 0x40, 0x3a, 0x32, 0x53, 0xa0,
	0xfa, 0xa1, 0x3c, 0xa5, 0x68, 0x2e, 0x7e, 0xcf, 0x94, 0xd4, 0xbc, 0x92, 0xcc, 0x92, 0x4a, 0xdf,
	0xd4, 0xe2, 0xe2, 0xc4, 0xf4, 0x54, 0x5c, 0x4a, 0x51, 0x1c, 0xc1, 0x84, 0xe6, 0x08, 0x11, 0x2e,
	0xd6, 0xd4, 0xdc, 0xc4, 0xcc, 0x1c, 0x09, 0x66, 0xb0, 0x04, 0x84, 0x93, 0xc4, 0x06, 0xf6, 0x8d,
	0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x5d, 0xf1, 0xe0, 0xb2, 0x0e, 0x01, 0x00, 0x00,
}
